### ISSUE TITLE
Remove Travis

### ISSUE THREAD

**Issue by SimonLab** [dwyl/useful#16]
Tests are pending on Travis:
![image](https://user-images.githubusercontent.com/6057298/170655544-57717c69-8eef-4ab9-93e3-3523cb1893a7.png)

- [ ] Make sure tests are not triggered on Travis when opening future PRs

**Comment by nelsonic** [comment]
Yeah, I saw that and dug in the settings to see if I could remove it but no luck after 2 mins of searching. 🔍  🤷‍♂️ 
Thank you for opening this issue. Linked to https://github.com/dwyl/learn-travis/issues/67 👍

**Comment by SimonLab** [comment]
I think I found why Travis was required: https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

![image](https://user-images.githubusercontent.com/6057298/180404266-ffb945bb-5522-4d75-9479-c98624ad4705.png)

I've removed the Travis rules for the branches, let see if this fix the issue

**Comment by nelsonic** [comment]
@SimonLab thanks for addressing and updating this issue in case we need to do this in other projects. 👍
