### ISSUE TITLE
stringify_map/1 converts a map to string for logging or easier transmission

### ISSUE THREAD

**Issue by nelsonic** [dwyl/useful#3]
We currently have a `stringify/1` function in `Auth.Log`:
https://github.com/dwyl/auth/blob/ee2ef5f97014e2eac8b8af05975dee664dfb60d2/lib/auth/log.ex#L127-L146

I think it makes sense to split this out into a `Useful` reusable function `stringify_map/1`.

+ [x] write tests for expected output
+ [x] implement `stringify_map/1` to stringify both `Map` and `Struct` data types
  + [x] accept map of arbitrary depth/nesting and flatten it to a single level using `flatten_map/1` function #2 
+ [x] publish new version of package to hex.pm

**Comment by vrcca** [comment]
Hi @nelsonic! I would like to work on this!

**Comment by nelsonic** [comment]
Added in #4 ✅
