### ISSUE TITLE
Bug: CompileError lib/useful.ex:24: Plug.Upload.__struct__/0 is undefined 🔥 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/useful#52]
As noted by @LuchoTurtle in https://github.com/dwyl/mvp/issues/406 and now confirmed in our other projects that use the `Useful` package:  https://github.com/dwyl/gogs/actions/runs/5863993387/job/15898337199#step:8:51
![image](https://github.com/dwyl/useful/assets/194400/4fc6aa3d-324e-4694-99b4-dcd0e541211c)

```sh
== Compilation error in file lib/useful.ex ==
Error: ** (CompileError) lib/useful.ex:24: Plug.Upload.__struct__/0 is undefined, 
cannot expand struct Plug.Upload. Make sure the struct name is correct. 
If the struct name exists and is correct but it still cannot be found, 
you likely have cyclic module usage in your code
could not compile dependency :useful, "mix compile" failed. 
Errors may have been logged above. 
You can recompile this dependency with "mix deps.compile useful", 
update it with "mix deps.update useful" 
or clean it with "mix deps.clean useful"
    expanding struct: Plug.Upload.__struct__/0
    lib/useful.ex:24: Useful.atomize_map_keys/1
```

We _either_ need to add `Plug` as dependency, not just `:dev` and `:test` the way it is now:
https://github.com/dwyl/useful/blame/35278cfb0c697cab555becfcc27ccf46731e61ee/mix.exs#L47-L48

***OR*** we need to define our own "dummy" Struct. 
But since the `Useful` package is used in at least one `Elixir` project that _isn't_ a `Phoenix` App,
I think we won't have any other choice but to make `Plug` a dependency. 💭 
Let's see how we can do this efficiently. 👌

**Comment by nelsonic** [comment]
I _thought_ a good starting point for trying to understand this is to search for `Plug.Upload` in our `imgup` project that _uses_ this struct: https://github.com/search?q=repo%3Adwyl%2Fimgup%20Plug.Upload&type=code

![image](https://github.com/dwyl/useful/assets/194400/09ea0ef5-43e3-440b-8ed6-4b448827f949)

But sadly it was not insightful. 💭

**Comment by nelsonic** [comment]
The version of `Plug` being used by `Phoenix` at the time of writing is `1.14`:
https://github.com/phoenixframework/phoenix/blob/e095f23ff62efb2f8c1205b0cc67bfacd80b11ed/mix.exs#L73

So I'm replacing:
https://github.com/dwyl/useful/blob/35278cfb0c697cab555becfcc27ccf46731e61ee/mix.exs#L48

with:
```elixir
{:plug, "~> 1.14"}
```

And will _alias_ the  `Plug.Upload` Struct in the `useful.ex` file.

**Comment by nelsonic** [comment]
Aliasing the `Plug.Upload` Struct does not appear to be used:

![image](https://github.com/dwyl/useful/assets/194400/3c2d268b-f478-4d61-83e2-7f96ad341097)

Going to remove it. ✂️

**Comment by nelsonic** [comment]
_Patch_ Package published to https://hex.pm/packages/useful/1.12.1 📦 
Tested in: https://github.com/dwyl/gogs/pull/75 ✅ 
No longer has compilation error. 

PR: #53 :shipit:

**Comment by LuchoTurtle** [comment]
Closing, as #53 was merged.
