### ISSUE TITLE
change a list of tuples with the same first element - key identifier  - into unique elements

### ISSUE THREAD

**Issue by ndrean** [dwyl/useful#59]
You want to modify `[{"a", 1}, {"a", 2},{"a",3}]` into `[{"a-3", 3}, {"a-2", 2}, {"a-1", 1}]`

**Why? ** 🤯 
When you receive a mulitpart form, you receive parts in the form `{key, headers, body}`. The "key" is the "name" attribute used in the input:  you will receive the same key for all of these inputs. Phoenix parses these parts into a map, so you understand that the key identifier must be unique (if you want all of them!).

The function below can turn theses inputs into unique ones, and allows multiple inputs.

You receive a list of tuples whose first element is the key you want to make unique. Name this list "parts":

```elixir
def make_unique_keys(parts) do
  key = parts |> hd() |> elem(0)
  new_keys = Enum.map(1..length(parts), &(key<>"-#{&1}"))

  new_keys = Enum.zip_reduce([parts,new_keys], [], fn [elt, new_key], acc->
    [
      elt |> Tuple.delete_at(0) |> Tuple.insert_at(0,new_key)
      | acc
    ]
  end)
end
```

**Comment by nelsonic** [comment]
This would be a good addition. If you have time, please PR. Thanks. 👌

**Comment by ndrean** [comment]
what name do you want to give?

**Comment by ndrean** [comment]
PR done

**Comment by nelsonic** [comment]
Naming things is tricky because it's a fine balance between being descriptive so people know exactly what the function does without having to look it up vs. being _too_ verbose and taking up an insane number of characters. 💭 

`transform_list_of_tuples_to_unique_keys/1` is descriptive but it's `39` characters ...
if the line length/limit in your team is `80` this doesn't leave a lot of room for argument names, piping, nesting, etc.

**Comment by ndrean** [comment]
or `list_of_tuples_to_unique_keys/1`, bit shorter, still expressive

**Comment by nelsonic** [comment]
@ndrean that's a good compromise. 👌

**Comment by ndrean** [comment]
https://github.com/dwyl/useful/pull/61

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/useful/1.14.0 contains this new function. 📦 🚀 
Thanks again @ndrean ❤️
